# =============================================================================
#  Simulation tables: each cell shows
#       mean
#      (SE)
#  using a two-line format inside the table cell.
# =============================================================================

sim    <- readRDS("simulation_results.rds")
N      <- sim$params$N_outer   # 10000
n_vals <- sim$params$n_vals
M_vals <- sim$params$M_vals
nc     <- length(M_vals)       # 4

# ------------------------------------------------------------------
# Format one cell as  value \\ (SE)  inside a \shortstack
# ------------------------------------------------------------------
.cell <- function(x) {
  if (is.na(x)) return("--")
  se  <- sqrt(x * (1 - x) / N)
  # value on first line, (SE) on second line, smaller font
  sprintf("\\shortstack{%.4f\\\\{\\footnotesize(%.4f)}}", x, se)
}

# ------------------------------------------------------------------
# Build one tabular with two-line cells
# For two-line cells we need extra row height: \arraystretch{1.8}
# ------------------------------------------------------------------
.tabular <- function(mat, lh, rh) {
  hdr <- paste0(
    "\\setlength{\\tabcolsep}{4.0pt}\n",
    "\\renewcommand{\\arraystretch}{1.80}\n",
    "\\begin{tabular}{@{}l cccc @{\\quad} cccc@{}}\n",
    "\\toprule\n",
    "& \\multicolumn{4}{c}{", lh, "}\n",
    "& \\multicolumn{4}{c}{", rh, "} \\\\\n",
    "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}\n",
    "$n$ & $M{=}1$ & $M{=}2$ & $M{=}5$ & $M{=}10$\n",
    "    & $M{=}1$ & $M{=}2$ & $M{=}5$ & $M{=}10$ \\\\\n",
    "\\midrule"
  )
  rows <- vapply(seq_along(n_vals), function(ni) {
    vals <- c(
      sapply(seq_len(nc),      function(j) .cell(mat[ni, j])),
      sapply(seq_len(nc) + nc, function(j) .cell(mat[ni, j]))
    )
    paste0(n_vals[ni], " & ", paste(vals, collapse = " & "), " \\\\")
  }, character(1L))
  footer <- "\\botrule\n\\end{tabular}"
  paste(c(hdr, rows, footer), collapse = "\n")
}

# ------------------------------------------------------------------
# Caption note
# ------------------------------------------------------------------
se_note <- paste0(
  "Each cell reports the estimated coverage probability (top) ",
  "and its Monte Carlo standard error ",
  "$\\mathrm{SE} = \\sqrt{\\hat{p}(1-\\hat{p})/N_{\\mathrm{outer}}}$ ",
  "(bottom, in parentheses). ",
  "$p = 4$, $\\alpha = 0.05$, ",
  "$N_{\\mathrm{outer}} = N_{\\mathrm{inner}} = 10\\,000$, ",
  "nominal level $0.95$."
)

# ------------------------------------------------------------------
# Build four tables
# ------------------------------------------------------------------
tab_gv <- .tabular(
  sim$gv,
  "\\textbf{GV} ($\\bm{\\Sigma}_3$, equicorrelation)",
  "\\textbf{GV} ($\\bm{\\Sigma}_4$, block structure)"
)
tab_sph <- .tabular(
  sim$sphericity,
  "\\textbf{Sphericity} ($\\bm{\\Sigma}_1$, $\\sigma^2{=}1$)",
  "\\textbf{Sphericity} ($\\bm{\\Sigma}_2$, $\\sigma^2{=}5$)"
)
tab_ind <- .tabular(
  sim$independence,
  "\\textbf{Independence} ($\\bm{\\Sigma}_1$, $p_1{=}1$)",
  "\\textbf{Independence} ($\\bm{\\Sigma}_4$, $p_1{=}2$)"
)
tab_reg <- .tabular(
  sim$regression,
  "\\textbf{Regression} ($\\bm{\\Sigma}_3$, $p_1{=}2$)",
  "\\textbf{Regression} ($\\bm{\\Sigma}_4$, $p_1{=}1$)"
)

# ------------------------------------------------------------------
# Write output file
# ------------------------------------------------------------------
make_table <- function(tab, label, cap_test, cap_H0, extra = "") {
  c(
    "\\begin{table}[!ht]",
    "\\centering",
    sprintf("\\caption{Empirical coverage probabilities for the %s", cap_test),
    sprintf("  procedure under $%s$.", cap_H0),
    if (nchar(extra) > 0) sprintf("  %s", extra),
    sprintf("  %s}", se_note),
    sprintf("\\label{%s}", label),
    tab,
    "\\end{table}"
  )
}

out_lines <- c(
  "% Auto-generated by make_sim_tables_se2.R",
  "% Cell format: coverage (top) / SE in parentheses (bottom)",
  "",
  make_table(tab_gv,  "tab:sim_gv",
             "generalised variance",
             "H_0 : |\\bm{\\Sigma}| = |\\bm{\\Sigma}_0|~(\\text{two-sided})"),
  "",
  make_table(tab_sph, "tab:sim_sph",
             "sphericity",
             "H_0 : \\bm{\\Sigma} = \\sigma^2\\bm{I}_4",
             "Near-identical columns for $\\bm{\\Sigma}_1$ and $\\bm{\\Sigma}_2$ confirm scale-invariance of $T_2^\\star$."),
  "",
  make_table(tab_ind, "tab:sim_ind",
             "independence",
             "H_0 : \\bm{\\Sigma}_{12} = \\bm{0}",
             "$\\bm{\\Sigma}_1$ ($p_1{=}1$): null holds trivially. $\\bm{\\Sigma}_4$ ($p_1{=}2$): null holds by construction."),
  "",
  make_table(tab_reg, "tab:sim_reg",
             "regression",
             "H_0 : \\bm{\\Delta} = \\bm{\\Delta}_0",
             "$\\bm{\\Delta}_0 = \\bm{\\Sigma}_{12}\\bm{\\Sigma}_{22}^{-1}$ computed from the true population covariance.")
)

writeLines(out_lines, "sim_tables_se2.tex")
cat("Written:", length(out_lines), "lines\n")

# Preview one row
cat("\nPreview (GV, n=10):\n")
x <- sim$gv[1,1]; se <- sqrt(x*(1-x)/N)
cat(sprintf("  %.4f  (%.4f)\n", x, se))

