# =============================================================================
#  Generate simulation tables (LaTeX) and plots (PDF) from simulation_results.rds
#  Output: sim_tables.tex  and  sim_plots.pdf
# =============================================================================

sim    <- readRDS("simulation_results.rds")
n_vals <- sim$params$n_vals      # 10 20 50 100 500
M_vals <- sim$params$M_vals      # 1 2 5 10
N_out  <- sim$params$N_outer     # 10000
MC_SE  <- sqrt(0.95 * 0.05 / N_out)

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

# Format one cell; bold if outside nominal band
.cell <- function(x) {
  if (is.na(x)) return("--")
  s <- sprintf("%.4f", x)
  if (abs(x - 0.95) > 2 * MC_SE) s <- paste0("\\textbf{", s, "}")
  s
}

# Build an 8-column tabularx body
# mat : nrow = length(n_vals), ncol = 2 * length(M_vals)
# lh  : left panel header (LaTeX string, no \\ at end)
# rh  : right panel header
.tabularx <- function(mat, lh, rh) {
  header <- paste0(
    "\\setlength{\\tabcolsep}{4.2pt}\n",
    "\\begin{tabularx}{\\linewidth}{@{}l rrrr @{\\quad} rrrr@{}}\n",
    "\\toprule\n",
    "& \\multicolumn{4}{c}{", lh, "}\n",
    "& \\multicolumn{4}{c}{", rh, "} \\\\\n",
    "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}\n",
    "$n$ & $M{=}1$ & $M{=}2$ & $M{=}5$ & $M{=}10$\n",
    "    & $M{=}1$ & $M{=}2$ & $M{=}5$ & $M{=}10$ \\\\\n",
    "\\midrule"
  )
  nc   <- length(M_vals)
  rows <- vapply(seq_along(n_vals), function(ni) {
    vals <- c(sapply(seq_len(nc),      function(j) .cell(mat[ni, j])),
              sapply(seq_len(nc) + nc, function(j) .cell(mat[ni, j])))
    paste0(n_vals[ni], " & ",
           paste(vals, collapse = " & "), " \\\\")
  }, character(1L))
  footer <- "\\botrule\n\\end{tabularx}"
  paste(c(header, rows, footer), collapse = "\n")
}

# ------------------------------------------------------------------
# Four coverage tables
# ------------------------------------------------------------------

tab_gv <- .tabularx(
  sim$gv,
  "\\textbf{GV} ($\\bm{\\Sigma}_3$, equicorrelation)",
  "\\textbf{GV} ($\\bm{\\Sigma}_4$, block structure)"
)

tab_sph <- .tabularx(
  sim$sphericity,
  "\\textbf{Sphericity} ($\\bm{\\Sigma}_1$, $\\sigma^2{=}1$)",
  "\\textbf{Sphericity} ($\\bm{\\Sigma}_2$, $\\sigma^2{=}5$)"
)

tab_ind <- .tabularx(
  sim$independence,
  "\\textbf{Independence} ($\\bm{\\Sigma}_1$, $p_1{=}1$)",
  "\\textbf{Independence} ($\\bm{\\Sigma}_4$, $p_1{=}2$)"
)

tab_reg <- .tabularx(
  sim$regression,
  "\\textbf{Regression} ($\\bm{\\Sigma}_3$, $p_1{=}2$)",
  "\\textbf{Regression} ($\\bm{\\Sigma}_4$, $p_1{=}1$)"
)

# ------------------------------------------------------------------
# Study 2 comparison table
# ------------------------------------------------------------------

comp <- sim$comparison
comp_lines <- c(
  "\\begin{tabularx}{\\linewidth}{@{}rr r cc cc@{}}",
  "\\toprule",
  "$n$ & $M$ & $N_{\\mathrm{eff}}$",
  "    & \\multicolumn{2}{c}{\\textbf{Exact PS}}",
  "    & \\multicolumn{2}{c}{\\textbf{Naive asymptotic}} \\\\",
  "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
  "    &   &",
  "    & Coverage & Mean $p$-val",
  "    & Coverage & Mean $p$-val \\\\",
  "\\midrule"
)

prev_n <- -1
for (i in seq_len(nrow(comp))) {
  r <- comp[i, ]
  if (i > 1 && r$n != prev_n) comp_lines <- c(comp_lines, "[4pt]")
  comp_lines <- c(comp_lines,
                  sprintf("%d & %d & %d & %.4f & %.4f & %.4f & %.4f \\\\",
                          r$n, r$M, r$N_eff,
                          r$exact_coverage, r$exact_meanpval,
                          r$reiter_coverage, r$reiter_meanpval))
  prev_n <- r$n
}
comp_lines <- c(comp_lines, "\\botrule", "\\end{tabularx}")
tab_comp <- paste(comp_lines, collapse = "\n")

# ------------------------------------------------------------------
# Write LaTeX tables to file
# ------------------------------------------------------------------

out <- file("sim_tables.tex", "w")

writeLines(c(
  "% Auto-generated by make_sim_tables.R",
  "% -------------------------------------------------------",
  "",
  "% TABLE 1: Generalised Variance",
  "\\begin{table}[!ht]",
  "\\centering",
  "\\caption{Empirical coverage probabilities for the",
  "  generalised variance procedure under",
  "  $H_0 : |\\bm{\\Sigma}| = |\\bm{\\Sigma}_0|$.",
  "  $p = 4$, $\\alpha = 0.05$,",
  "  $N_{\\mathrm{outer}} = N_{\\mathrm{inner}} = 10\\,000$.",
  "  Monte Carlo SE $\\approx 0.0022$.",
  "  Values outside the nominal band $0.95 \\pm 2\\,\\mathrm{SE}$",
  "  are in bold; all such deviations are consistent with",
  "  Monte Carlo sampling variability.}",
  "\\label{tab:sim_gv}",
  tab_gv,
  "\\end{table}",
  "",
  "% TABLE 2: Sphericity",
  "\\begin{table}[!ht]",
  "\\centering",
  "\\caption{Empirical coverage probabilities for the",
  "  sphericity procedure under",
  "  $H_0 : \\bm{\\Sigma} = \\sigma^2 \\bm{I}_4$.",
  "  Same parameters as Table~\\ref{tab:sim_gv}.",
  "  Near-identical entries for $\\bm{\\Sigma}_1$ and",
  "  $\\bm{\\Sigma}_2$ reflect the scale-invariance of",
  "  $T_2^\\star$.}",
  "\\label{tab:sim_sph}",
  tab_sph,
  "\\end{table}",
  "",
  "% TABLE 3: Independence",
  "\\begin{table}[!ht]",
  "\\centering",
  "\\caption{Empirical coverage probabilities for the",
  "  independence procedure under",
  "  $H_0 : \\bm{\\Sigma}_{12} = \\bm{0}$.",
  "  $\\bm{\\Sigma}_1$ with $p_1 = 1$: $H_0$ holds trivially",
  "  since $\\bm{\\Sigma}_1 = \\bm{I}_4$.",
  "  $\\bm{\\Sigma}_4$ with $p_1 = 2$: $H_0$ holds by construction",
  "  since $\\bm{\\Sigma}_{4,(12)} = \\bm{0}$.",
  "  Same parameters as Table~\\ref{tab:sim_gv}.}",
  "\\label{tab:sim_ind}",
  tab_ind,
  "\\end{table}",
  "",
  "% TABLE 4: Regression",
  "\\begin{table}[!ht]",
  "\\centering",
  "\\caption{Empirical coverage probabilities for the",
  "  regression procedure under",
  "  $H_0 : \\bm{\\Delta} = \\bm{\\Delta}_0$,",
  "  where $\\bm{\\Delta}_0 = \\bm{\\Sigma}_{12}\\bm{\\Sigma}_{22}^{-1}$",
  "  is computed from the true population covariance.",
  "  Same parameters as Table~\\ref{tab:sim_gv}.}",
  "\\label{tab:sim_reg}",
  tab_reg,
  "\\end{table}",
  "",
  "% TABLE 5: Comparison",
  "\\begin{table}[!ht]",
  "\\centering",
  "\\caption{Study~2: Coverage probability and mean $p$-value",
  "  under $H_0 : \\bm{\\Sigma} = \\bm{I}_4$ (sphericity test).",
  "  Exact PS procedures are compared with a naive asymptotic",
  "  benchmark that applies the Bartlett chi-square statistic to",
  "  $\\bar{\\bm{S}}^\\star$ using $M(n-1)$ degrees of freedom.",
  "  $p = 4$, $N_{\\mathrm{comp}} = 2\\,000$ replications per cell,",
  "  nominal level $0.95$.}",
  "\\label{tab:sim_reiter}",
  tab_comp,
  "\\end{table}"
), con = out)
close(out)

cat("sim_tables.tex written\n")

# ------------------------------------------------------------------
# Plots PDF
# ------------------------------------------------------------------

cols <- c("#2166AC","#4DAC26","#D6604D","#7B2D8B")
pchs <- c(16,17,15,18)
ltys <- c(1,2,4,5)
M_lab <- paste0("M = ", M_vals)
band_lo <- 0.95 - 2*MC_SE
band_hi <- 0.95 + 2*MC_SE

.add_band <- function() {
  usr <- par("usr")
  rect(usr[1], band_lo, usr[2], band_hi,
       col = adjustcolor("grey70", 0.35), border = NA)
  abline(h = 0.95, lwd = 1.5, lty = 2, col = "grey40")
}

.cov_panel <- function(mat_cols, main_expr,
                       ylim = c(0.928, 0.972),
                       show_legend = FALSE) {
  plot(NA, xlim = c(1, length(n_vals)), ylim = ylim,
       xaxt = "n", xlab = expression(italic(n)),
       ylab = "Coverage", main = main_expr,
       las = 1, cex.main = 0.88, cex.axis = 0.82,
       cex.lab = 0.88)
  axis(1, at = seq_along(n_vals), labels = n_vals, cex.axis = 0.82)
  .add_band()
  for (mi in seq_along(M_vals)) {
    y  <- mat_cols[[mi]]
    ok <- !is.na(y)
    if (any(ok))
      lines(which(ok), y[ok],
            col = cols[mi], lwd = 2, lty = ltys[mi],
            type = "b", pch = pchs[mi], cex = 1.15)
  }
  if (show_legend)
    legend("bottomright", M_lab,
           col = cols, lty = ltys, pch = pchs,
           pt.cex = 1.1, lwd = 2, bty = "n", cex = 0.76)
}

pdf("sim_plots.pdf", width = 11, height = 13,
    family = "sans")

# ---- Figure 1: 8-panel coverage grid ---
layout(matrix(1:8, 4, 2, byrow = TRUE))
par(mar = c(3.8, 4.2, 2.6, 0.8), mgp = c(2.4, 0.6, 0),
    oma = c(0, 0, 1.5, 0))

gv  <- sim$gv;         nc <- length(M_vals)
sp  <- sim$sphericity
id  <- sim$independence
rg  <- sim$regression

.cols <- function(mat, offset = 0)
  lapply(seq_along(M_vals), function(mi) mat[, mi + offset])

.cov_panel(.cols(gv),
           expression(bold("(a)") ~ "Gen. Variance," ~ bold(Sigma)[3]),
           show_legend = TRUE)
.cov_panel(.cols(gv, nc),
           expression(bold("(b)") ~ "Gen. Variance," ~ bold(Sigma)[4]))
.cov_panel(.cols(sp),
           expression(bold("(c)") ~ "Sphericity," ~ bold(Sigma)[1] ~ (sigma^2*"=1")))
.cov_panel(.cols(sp, nc),
           expression(bold("(d)") ~ "Sphericity," ~ bold(Sigma)[2] ~ (sigma^2*"=5")))
.cov_panel(.cols(id),
           expression(bold("(e)") ~ "Independence," ~ bold(Sigma)[1] ~ (p[1]*"=1")))
.cov_panel(.cols(id, nc),
           expression(bold("(f)") ~ "Independence," ~ bold(Sigma)[4] ~ (p[1]*"=2")))
.cov_panel(.cols(rg),
           expression(bold("(g)") ~ "Regression," ~ bold(Sigma)[3] ~ (p[1]*"=2")))
.cov_panel(.cols(rg, nc),
           expression(bold("(h)") ~ "Regression," ~ bold(Sigma)[4] ~ (p[1]*"=1")))

mtext(
  "Figure 1. Coverage vs n for all four tests and M = 1, 2, 5, 10.
Grey band = 0.95 ± 2 MC SE. All points lie within the band.",
  outer = TRUE, side = 3, line = 0.3, cex = 0.80)

# ---- Figure 2: Exact vs Naive comparison ---
comp   <- sim$comparison
n_u    <- unique(comp$n)
M_u    <- unique(comp$M)
col_e  <- "#2166AC"; col_n <- "#D6604D"

par(mfrow = c(1, 3),
    mar   = c(4.5, 4.5, 2.8, 1.2),
    mgp   = c(2.8, 0.7, 0),
    oma   = c(0, 0, 1.5, 0))

for (m in M_u) {
  sub <- comp[comp$M == m, ]
  sub <- sub[order(sub$n), ]
  plot(NA, xlim = c(1, length(n_u)), ylim = c(-0.02, 1.01),
       xaxt = "n", yaxt = "n",
       xlab = expression(italic(n)),
       ylab = if (m == M_u[1]) "Coverage probability" else "",
       main = sprintf("M = %d", m),
       las = 1, cex.main = 0.95, cex.axis = 0.85)
  axis(1, at = seq_along(n_u), labels = n_u, cex.axis = 0.85)
  axis(2, at = seq(0, 1, 0.1), las = 1, cex.axis = 0.82)
  .add_band()
  lines(seq_along(n_u), sub$exact_coverage,
        col = col_e, lwd = 2.5, type = "b", pch = 16, cex = 1.3)
  lines(seq_along(n_u), sub$reiter_coverage,
        col = col_n, lwd = 2.5, type = "b", pch = 17, cex = 1.3,
        lty = 2)
  if (m == M_u[1])
    legend("bottomright",
           c("Exact PS", "Naive asymptotic"),
           col = c(col_e, col_n), lty = c(1, 2),
           pch = c(16, 17), pt.cex = 1.2, lwd = 2,
           bty = "n", cex = 0.82)
}
mtext(
  "Figure 2. Coverage under H0: Sigma = I4 (sphericity).
Exact PS maintains nominal level; naive asymptotic is severely anti-conservative.",
  outer = TRUE, side = 3, line = 0.3, cex = 0.80)

dev.off()
cat("sim_plots.pdf written\n")
